theme = "dracula"
# default spotify client
#client_id = "65b708073fc0480ea92a077233ca87bd"
# my client id 
client_id = "3fc0e41b3f914ad396e7e8394aacf9ab"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
playback_window_width = 6
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "gentoo"

[copy_command]
command = "xclip"
args = [
    "-sel",
    "c",
]

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "gentoo"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
backend = "sdl"
